# -*- coding: utf-8 -*-

import sys, os, time
import configparser,unittest
from packages.HTMLTestRunner import HTMLTestRunner

# def get_config():
#     config_file_name = './config/config.ini'
#     config_file = open(config_file_name, 'r')
#     config = configparser.ConfigParser()
#     config.read_file(config_file)
#     baseurl = config.get("base", "baseurl")
#     username = config.get("base", "user")
#     passwd = config.get("base", "passwd")
#     return baseurl,username,passwd
#     config_file.close()

if __name__ == "__main__":
    suite = unittest.TestSuite()
    # test_case_list = [ i for i in os.listdir("./test_case") if i.startswith("test") ]
    # for case in test_case_list:
    #     suite.addTest()
    # runner = unittest.TestLoader().discover('test_case')
    # suite.addTest(runner)
    # with open('./report/HTMLReport.html', 'wb') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='My Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2)
    #     runner.run(suite)
    # f.close()

    runner = unittest.TestLoader().discover('test_case')
    unittest.TextTestRunner(verbosity=2).run(runner)