# -*- coding: utf-8 -*-

import sys, os, time

from packages.HTMLTestRunner import HTMLTestRunner
import configparser,unittest
from selenium import webdriver

config_file_name = './config/config.ini'
config_file = open(config_file_name, 'r')
config = configparser.ConfigParser()
config.read_file(config_file)

baseurl = config.get("base","baseurl")
#print(baseurl)

class Mytest(unittest.TestCase):
    def setUp(self) -> None:
        self.browser = webdriver.Chrome()
        self.browser.get(baseurl)

    def test_1(self):
        time.sleep(5)
        brower = self.browser
        title = brower.title
        self.assertEqual(title,'PAXSTORE','title is right!')


    def tearDown(self) -> None:
        self.browser.close()

config_file.close()

suite = unittest.TestSuite()
suite.addTest(Mytest("test_1"))
# with open('./report/HTMLReport.html', 'wb') as f:
#     runner = HTMLTestRunner(stream=f,title='My Test Report',description='generated by HTMLTestRunner.',verbosity=2)
#     runner.run(suite)
# f.close()

runner = unittest.TextTestRunner(verbosity=2)
runner.run(suite)